In [5]:
#1D array
import numpy as np
np.array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
#from tuple
import numpy as np
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [9]:
#multi-dimensional
import numpy as np
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
#arange
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#linespace
import numpy as np
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [13]:
#zeros
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
#ones
import numpy as np
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
#random
import numpy as np
np.random.rand(5)

array([0.09724736, 0.34516441, 0.51489426, 0.48532909, 0.90345462])

In [19]:
#random integer
import numpy as np
a=np.random.randint(5,size=20)

In [20]:
a


array([0, 1, 3, 0, 3, 2, 2, 4, 0, 4, 4, 4, 2, 0, 1, 2, 0, 4, 3, 1])

In [26]:
#size
a.size

20

In [27]:
#len
len(a)

20

In [28]:
#shape
a.shape

(20,)

In [32]:
#datatype
a.dtype

dtype('int32')

In [34]:
#sort
import numpy as np
np.sort(a)

array([0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4])

In [35]:
#append
import numpy as np
np.append(a,[8])

array([0, 1, 3, 0, 3, 2, 2, 4, 0, 4, 4, 4, 2, 0, 1, 2, 0, 4, 3, 1, 8])

In [38]:
import numpy as np
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
#reshape
import numpy as np
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
#sqrt
import numpy as np
np.sqrt(9)

3.0

In [49]:
#log
import numpy as np
np.log(a)

C:\Users\Anuja Sunil Kulkarni\AppData\Local\Temp\ipykernel_1644\2018000918.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 1.09861229,       -inf, 1.09861229,
       0.69314718, 0.69314718, 1.38629436,       -inf, 1.38629436,
       1.38629436, 1.38629436, 0.69314718,       -inf, 0.        ,
       0.69314718,       -inf, 1.38629436, 1.09861229, 0.        ])

In [46]:
#absolute
import numpy as np
np.absolute(a)

array([0, 1, 3, 0, 3, 2, 2, 4, 0, 4, 4, 4, 2, 0, 1, 2, 0, 4, 3, 1])

In [48]:
#sine
import numpy as np
np.sin(a)

array([ 0.        ,  0.84147098,  0.14112001,  0.        ,  0.14112001,
        0.90929743,  0.90929743, -0.7568025 ,  0.        , -0.7568025 ,
       -0.7568025 , -0.7568025 ,  0.90929743,  0.        ,  0.84147098,
        0.90929743,  0.        , -0.7568025 ,  0.14112001,  0.84147098])

In [50]:
#cos
import numpy as np
np.cos(a)

array([ 1.        ,  0.54030231, -0.9899925 ,  1.        , -0.9899925 ,
       -0.41614684, -0.41614684, -0.65364362,  1.        , -0.65364362,
       -0.65364362, -0.65364362, -0.41614684,  1.        ,  0.54030231,
       -0.41614684,  1.        , -0.65364362, -0.9899925 ,  0.54030231])

In [51]:
#round
import numpy as np
np.round(a)

array([0, 1, 3, 0, 3, 2, 2, 4, 0, 4, 4, 4, 2, 0, 1, 2, 0, 4, 3, 1])

In [52]:
#mean
import numpy as np
np.mean(a)

2.0

In [53]:
#median
import numpy as np
np.median(a)

2.0

In [54]:
#sum
import numpy as np
np.sum(a)

40

In [55]:
#max
import numpy as np
np.max(a)

4

In [56]:
#min
import numpy as np
np.min(a)

0

In [57]:
#variance
import numpy as np
np.var(a)

2.3

In [58]:
#standard deviation
import numpy as np
np.std(a)

1.51657508881031

In [59]:
#correlation coeff
import numpy as np
np.corrcoef(a)

1.0