# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [10]:
import numpy as np
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [12]:
import numpy as np
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

#### Create an array of the integers from 10 to 50

In [13]:
import numpy as np
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [1]:
import numpy as np
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [2]:
import numpy as np
np.array([[[0,1,2],[3,4,5],[6,7,8]]])

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

#### Create a 3x3 identity matrix

In [3]:
import numpy as np
np.array([[[1,0,0,],[0,1,0],[0,0,1]]])

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

#### Use NumPy to generate a random number between 0 and 1

In [4]:
import numpy as np
s=np.random.normal(0,1)
print(s)

-0.11339246309208956


 Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
import numpy as np
a=np.random.randn(25)
a

array([ 0.00475138,  0.25772002, -1.05467878,  0.20611116, -0.69747965,
        0.65424612,  0.42080728, -0.30013194, -0.03822172, -0.85623965,
        1.48763233,  0.09224381,  0.7706232 ,  1.03444822, -0.13935035,
        0.91210042,  0.57263206, -1.91683775, -0.40217354, -0.025861  ,
       -0.48406891, -0.15218613,  0.62219347,  1.12913853, -0.74764519])

#### Create the following matrix:

In [19]:
import numpy as np
a=np.arange()

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [83]:
import numpy as np
a=np.arange(0,1.2,0.0101000)
a

array([0.    , 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707,
       0.0808, 0.0909, 0.101 , 0.1111, 0.1212, 0.1313, 0.1414, 0.1515,
       0.1616, 0.1717, 0.1818, 0.1919, 0.202 , 0.2121, 0.2222, 0.2323,
       0.2424, 0.2525, 0.2626, 0.2727, 0.2828, 0.2929, 0.303 , 0.3131,
       0.3232, 0.3333, 0.3434, 0.3535, 0.3636, 0.3737, 0.3838, 0.3939,
       0.404 , 0.4141, 0.4242, 0.4343, 0.4444, 0.4545, 0.4646, 0.4747,
       0.4848, 0.4949, 0.505 , 0.5151, 0.5252, 0.5353, 0.5454, 0.5555,
       0.5656, 0.5757, 0.5858, 0.5959, 0.606 , 0.6161, 0.6262, 0.6363,
       0.6464, 0.6565, 0.6666, 0.6767, 0.6868, 0.6969, 0.707 , 0.7171,
       0.7272, 0.7373, 0.7474, 0.7575, 0.7676, 0.7777, 0.7878, 0.7979,
       0.808 , 0.8181, 0.8282, 0.8383, 0.8484, 0.8585, 0.8686, 0.8787,
       0.8888, 0.8989, 0.909 , 0.9191, 0.9292, 0.9393, 0.9494, 0.9595,
       0.9696, 0.9797, 0.9898, 0.9999, 1.01  , 1.0201, 1.0302, 1.0403,
       1.0504, 1.0605, 1.0706, 1.0807, 1.0908, 1.1009, 1.111 , 1.1211,
      

Create an array of 20 linearly spaced points between 0 and 1:

In [43]:
import numpy as np
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [44]:
import numpy as np
a=np.arange(1,26,1)
b=a.reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [60]:
import numpy as np
a= np.arange(1, 26).reshape(5, 5)
b=a[1:, 1:]
print(b)



[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [61]:
import numpy as np
a= np.arange(1, 26).reshape(5, 5)
b=a[1:, 1:]
print(b)


[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [64]:
import numpy as np
a=np.array([[[2],[7],[12]]])
a

array([[[ 2],
        [ 7],
        [12]]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [66]:
import numpy as np
s=np.array([21,22,23,24,25])
s

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [75]:
import numpy as np
a=np.array([[16,17,18,19,20],[21,22,23,24,25]])

### Now do the following

 Get the sum of all the values in mat

array([], dtype=int32)

Get the standard deviation of the values in mat

In [79]:
import numpy as np
a=([55,60,65,70,75])
np.std(a)

7.0710678118654755

#### Get the sum of all the columns in mat

In [76]:
import numpy as np
a=([55,60,65,70,75])
np.sum(a)

325

# Great Job!